{{- if .Values.traefik.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: observer
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`observer.{{ .Values.global.baseDomain }}`)
      kind: Rule
      services:
        - name: observer
          port: 8080
          scheme: http
{{- end }}
